from server.lifespans.consul_register import consul_register as consul_register
from server.lifespans.load_fasttext_model import load_fasttext_model as load_fasttext_model
from server.lifespans.load_translator_model import load_translator_model as load_translator_model
