[project]
name = "language"
requires-python = ">=3.14.7, <3.15"
dynamic = ["version"]
dependencies = ["fasttext>=0.9.3"]
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

[dependency-groups]
dev = ["maturin>=1.15.0"]

[build-system]
requires = ["maturin>=1.15.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3/extension-module"]
exclude = ["**/uv.lock"]
