name: Clippy

on:
  pull_request:
  push:
    branches: [main]
    paths:
      - .github/workflows/clippy.yml
      - client/**
      - language/**

jobs:
  clippy:
    uses: winstxnhdw/actions/.github/workflows/rust.yml@10339f0c31654e18c00d8c7256351ba78bcb2ef7 # main
    with:
      working-directory: ${{ matrix.working-directory }}
      disable-test: true
    strategy:
      matrix:
        working-directory: [client, language]
