name: Clippy

on:
  pull_request:
  push:
    branches: [main]
    paths:
      - .github/workflows/clippy.yml
      - client/**
      - language/**

jobs:
  clippy:
    uses: winstxnhdw/actions/.github/workflows/rust.yml@f43de6b5804c7609cb6f13864e2d18a70301469e # main
    with:
      working-directory: ${{ matrix.working-directory }}
      disable-test: true
    strategy:
      matrix:
        working-directory: [client, language]
