name: Clippy

on:
  pull_request:
  push:
    branches: [main]
    paths:
      - .github/workflows/clippy.yml
      - client/**
      - language/**

jobs:
  clippy:
    uses: winstxnhdw/actions/.github/workflows/rust.yml@4d514e9cc5ee4206069ba3216a5751f08938e355 # main
    with:
      working-directory: ${{ matrix.working-directory }}
      disable-test: true
    strategy:
      matrix:
        working-directory: [client, language]
