name: CUDA

on:
  pull_request:
  push:
    paths:
      - .github/workflows/cuda.yml
      - .dockerignore
      - Dockerfile.build
      - uv.lock
      - pyproject.toml
      - server/**
      - language/**

jobs:
  build:
    uses: winstxnhdw/actions/.github/workflows/docker-build.yml@616389d9e449f2a129b80276e49f084812180f4a # main
    with:
      file: Dockerfile.build
      cache-mode: min
      build-args: |
        USE_CUDA=1
