name: CUDA

on:
  pull_request:
  push:
    paths:
      - .github/workflows/cuda.yml
      - .dockerignore
      - Dockerfile.build
      - uv.lock
      - pyproject.toml
      - server/**
      - language/**

jobs:
  build:
    uses: winstxnhdw/actions/.github/workflows/docker-build.yml@0832d473774c1447617374fce8cf68e75c50dd7f # main
    with:
      file: Dockerfile.build
      cache-mode: min
      build-args: |
        USE_CUDA=1
