name: CUDA

on:
  pull_request:
  push:
    paths:
      - .github/workflows/cuda.yml
      - .dockerignore
      - Dockerfile.build
      - uv.lock
      - pyproject.toml
      - server/**
      - language/**

jobs:
  build:
    uses: winstxnhdw/actions/.github/workflows/docker-build.yml@4d514e9cc5ee4206069ba3216a5751f08938e355 # main
    with:
      file: Dockerfile.build
      cache-mode: min
      build-args: |
        USE_CUDA=1
