name: Deploy

on:
  push:
    branches: [main]
    paths: [Dockerfile]

jobs:
  deploy:
    uses: winstxnhdw/actions/.github/workflows/spaces-deploy.yml@4d514e9cc5ee4206069ba3216a5751f08938e355 # main
    secrets:
      token: ${{ secrets.HF_TOKEN }}
