name: Deploy

on:
  push:
    branches: [main]
    paths: [Dockerfile]

jobs:
  deploy:
    uses: winstxnhdw/actions/.github/workflows/spaces-deploy.yml@616389d9e449f2a129b80276e49f084812180f4a # main
    secrets:
      token: ${{ secrets.HF_TOKEN }}
