name: Deploy

on:
  push:
    branches: [main]
    paths: [Dockerfile]

jobs:
  deploy:
    uses: winstxnhdw/actions/.github/workflows/spaces-deploy.yml@f43de6b5804c7609cb6f13864e2d18a70301469e # main
    secrets:
      token: ${{ secrets.HF_TOKEN }}
