name: Format

on:
  push:
    paths:
      - .github/workflows/formatter.yml
      - pyproject.toml
      - uv.lock
      - server/**

permissions:
  contents: write

jobs:
  format:
    uses: winstxnhdw/actions/.github/workflows/format-python.yml@f43de6b5804c7609cb6f13864e2d18a70301469e # main
