name: Format

on:
  push:
    paths:
      - .github/workflows/formatter.yml
      - pyproject.toml
      - uv.lock
      - server/**

permissions:
  contents: write

jobs:
  format:
    uses: winstxnhdw/actions/.github/workflows/format-python.yml@0832d473774c1447617374fce8cf68e75c50dd7f # main
