name: Format

on:
  push:
    paths:
      - .github/workflows/formatter.yml
      - pyproject.toml
      - uv.lock
      - server/**

permissions:
  contents: write

jobs:
  format:
    uses: winstxnhdw/actions/.github/workflows/format-python.yml@616389d9e449f2a129b80276e49f084812180f4a # main
